import bcrypt from 'bcryptjs';
import { dateInCurrentMonth, nowIso } from '../utils/date.js';

export function createSeedData(email, password) {
  const createdAt = nowIso();
  return {
    users: [
      {
        id: 'user-chad',
        email,
        password_hash: bcrypt.hashSync(password, 10),
        role: 'admin',
        name: 'Chad',
      },
    ],
    staff: [
      {
        id: 'staff-pt-001',
        staff_code: 'PT001',
        name: 'Alicia Lim',
        phone: '6591234567',
        employment_type: 'part_time',
        role: 'Medic',
        active: true,
      },
      {
        id: 'staff-pt-002',
        staff_code: 'PT002',
        name: 'Marcus Tan',
        phone: '6582345678',
        employment_type: 'part_time',
        role: 'Driver',
        active: true,
      },
      {
        id: 'staff-pt-003',
        staff_code: 'PT003',
        name: 'Nur Aisyah',
        phone: '6598761234',
        employment_type: 'part_time',
        role: 'EMT',
        active: true,
      },
    ],
    availability: [
      {
        id: 'availability-001',
        staff_id: 'staff-pt-001',
        available_date: dateInCurrentMonth(1),
        period: 'AM',
        start_time: '06:00',
        end_time: '12:00',
        note: 'Available before afternoon class',
        coverage_gap: false,
        deleted_at: null,
        created_at: createdAt,
        updated_at: createdAt,
      },
      {
        id: 'availability-002',
        staff_id: 'staff-pt-002',
        available_date: dateInCurrentMonth(2),
        period: 'FULL_DAY',
        start_time: '06:00',
        end_time: '22:00',
        note: '',
        coverage_gap: false,
        deleted_at: null,
        created_at: createdAt,
        updated_at: createdAt,
      },
      {
        id: 'availability-003',
        staff_id: 'staff-pt-003',
        available_date: dateInCurrentMonth(3),
        period: 'PM',
        start_time: '12:00',
        end_time: '22:00',
        note: 'Morning unavailable',
        coverage_gap: true,
        deleted_at: null,
        created_at: createdAt,
        updated_at: createdAt,
      },
    ],
    exceptions: [
      {
        id: 'exception-001',
        type: 'HALF_DAY_GAP',
        severity: 'warning',
        shift_date: dateInCurrentMonth(3),
        shift_start: '06:00',
        shift_end: '12:00',
        staff_id: 'staff-pt-003',
        summary: 'Morning coverage still needs a replacement',
        recommendation: 'Contact an available part-timer for the AM slot',
        status: 'active',
        resolution_note: null,
        deferred_until: null,
        resolved_by: null,
        resolved_at: null,
        created_at: createdAt,
        updated_at: createdAt,
      },
      {
        id: 'exception-002',
        type: 'EMPTY_SHIFT',
        severity: 'critical',
        shift_date: dateInCurrentMonth(4),
        shift_start: '14:00',
        shift_end: '22:00',
        staff_id: null,
        summary: 'No eligible medic found for the afternoon shift',
        recommendation: 'Review part-timer availability or reject the case',
        status: 'active',
        resolution_note: null,
        deferred_until: null,
        resolved_by: null,
        resolved_at: null,
        created_at: createdAt,
        updated_at: createdAt,
      },
      {
        id: 'exception-003',
        type: 'SEVENTH_DAY',
        severity: 'warning',
        shift_date: dateInCurrentMonth(5),
        shift_start: '06:00',
        shift_end: '14:00',
        staff_id: 'staff-pt-002',
        summary: 'Staff member is scheduled for a seventh consecutive day',
        recommendation: 'Confirm the assignment or swap the staff member',
        status: 'deferred',
        resolution_note: 'Review again after the morning roster is confirmed',
        deferred_until: dateInCurrentMonth(1),
        resolved_by: null,
        resolved_at: null,
        created_at: createdAt,
        updated_at: createdAt,
      },
    ],
    audit: [
      {
        id: 'audit-001',
        exception_id: 'exception-003',
        action: 'defer',
        previous_status: 'active',
        new_status: 'deferred',
        note: 'Review again after the morning roster is confirmed',
        actor_email: email,
        created_at: createdAt,
      },
    ],
  };
}
